### ISSUE TITLE
multi-domain question

### ISSUE THREAD

**Issue by fradino** [songquanpeng/L2M-GAN#1]
hello, i have a question about multi-domains that how can i change the gender and expression at the same time please. thank you

**Comment by songquanpeng** [comment]
You will have to split the dataset into four domains:
1. male, not smiling
2. male, smiling
3. female, not smiling
4. female, smiling

**Comment by fradino** [comment]
> You will have to split the dataset into four domains:
> 
> 1. male, not smiling
> 2. male, smiling
> 3. female, not smiling
> 4. female, smiling

thank you very much! very helpful!
