### ISSUE TITLE
mulit-domains (more than 2)

### ISSUE THREAD

**Issue by guofeicv** [songquanpeng/L2M-GAN#2]
hello,  i also have a question about multi-domains  that f i want to modify three attributes or more ,what should i do? Should i have to split the dataset into 2^3 eight domains? thank you

**Comment by songquanpeng** [comment]
Yes, for L2M-GAN i think so. Each different attributes combination is a different domain.

**Comment by guofeicv** [comment]
ok, thanks a lot.
