### ISSUE TITLE
the design of style transformer

### ISSUE THREAD

**Issue by fido20160817** [songquanpeng/L2M-GAN#3]
Hi, Quanpeng Song. The author gives no clues about the net structure of style transformer, so I am wondering how you design the style transformer in your code and why it can work. Can you share something? I am curious about the design of network. Hope you can share some with me.

**Comment by songquanpeng** [comment]
Actually they have given the description, plz check the supplemental: https://openaccess.thecvf.com/content/CVPR2021/supplemental/Yang_L2M-GAN_Learning_To_CVPR_2021_supplemental.pdf

**Comment by songquanpeng** [comment]
In case you don't know, there is an official implementation: https://github.com/rucmlcv/L2M-GAN

I didn't find it when i craft my own implementation 😅.

**Comment by fido20160817** [comment]
got it! many thanks!Best!Hao发自我的iPhone------------------ Original ------------------From: JustSong  ***@***.***>Date: Sat,Jan 8,2022 9:30 PMTo: songquanpeng/L2M-GAN ***@***.***>Cc: Hao Ma ***@***.***>, Author ***@***.***>Subject: Re: [songquanpeng/L2M-GAN] the design of style transformer (Issue #3)
Actually they given the discription, plz check the supplemental: https://openaccess.thecvf.com/content/CVPR2021/supplemental/Yang_L2M-GAN_Learning_To_CVPR_2021_supplemental.pdf

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/songquanpeng/L2M-GAN/issues/3#issuecomment-1007990255",
"url": "https://github.com/songquanpeng/L2M-GAN/issues/3#issuecomment-1007990255",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
