### ISSUE TITLE
您好，请问我这么实现reference-guided生成思路对吗，希望大佬可以抽几分钟指点一下

### ISSUE THREAD

**Issue by zhushuqi2333** [songquanpeng/L2M-GAN#5]
大佬您好，我看了您的代码，里面是用label生成图片的，我想实现用参考图像引导图片生成，目前思路是这样的，直接用Style_encoder提取参考图像的s_trg，然后将x和s_trg传入生成器生成目标图片。但是这么做就跳过了Style_transformer，所以我的思路对吗，还是说有更合理的做法，期待您的回复！

**Comment by songquanpeng** [comment]
看下这个：https://github.com/clovaai/stargan-v2

**Comment by zhushuqi2333** [comment]
> 看下这个：https://github.com/clovaai/stargan-v2

好的 谢谢你！
