### ISSUE TITLE
how can I run the evaluate and sample code?

### ISSUE THREAD

**Issue by Zrc007** [songquanpeng/L2M-GAN#6]
how can I run the evaluate and sample code?

**Comment by songquanpeng** [comment]
Set the mode to the corresponding value.
```python
  if args.mode == 'train':
      loaders = Munch(train=get_train_loader(**args), test=get_test_loader(**args))
      if args.selected_path:
          loaders.selected = get_selected_loader(**args)
      solver.train(loaders)
  elif args.mode == 'sample':
      solver.sample()
  elif args.mode == 'eval':
      solver.evaluate()
```

**Comment by songquanpeng** [comment]
You will have to check the corresponding code, I don't have a complete shell script example right now.

**Comment by Zrc007** [comment]
Thanks for your prompt reply, I see your result of experiment #1 and #2, I wanna know do you run the evaluate code of the 
project(https://github.com/rucmlcv/L2M-GAN), such as CUDA_VISIBLE_DEVICES=0 python main.py --num_domains 2 --w_hpf 1 --resume_iter 100000 --train_img_dir data/celeba_hq/train --val_img_dir data/celeba_hq/val --checkpoint_dir /expr/checkpoints --eval_dir expr/eval. Is it runnable?

**Comment by songquanpeng** [comment]
Actually, I don't run that project's evaluation script.  When I code this project, I don't know there is an official one available. The results reported in the readme are from my own evaluation code.

**Comment by Zrc007** [comment]
bro, do you have the enviroment list,thx

**Comment by songquanpeng** [comment]
What is environment list? environment .yml for conda env?

**Comment by Zrc007** [comment]
environment.yml is ok, or a list of the used package version

**Comment by songquanpeng** [comment]
Check this out: https://github.com/songquanpeng/L2M-GAN/blob/master/requirements.txt

**Comment by Zrc007** [comment]
could you give the scipy version, because I have tried some but none sence. The error is so:
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from solver.solver import Solver
  File "C:\Users\Temp2\Desktop\L2M-GAN-master\solver\solver.py", line 11, in <module>
    from models.build import build_model
  File "C:\Users\Temp2\Desktop\L2M-GAN-master\models\build.py", line 7, in <module>
    from models.fan import FAN
  File "C:\Users\Temp2\Desktop\L2M-GAN-master\models\fan.py", line 21, in <module>
    from skimage.filters import gaussian
  File "C:\Users\Temp2\anaconda3\envs\L2M-GAN\lib\site-packages\skimage\filters\__init__.py", line 3, in <module>
    from .edges import (sobel, sobel_h, sobel_v,
  File "C:\Users\Temp2\anaconda3\envs\L2M-GAN\lib\site-packages\skimage\filters\edges.py", line 15, in <module>
    from scipy.ndimage import convolve, binary_erosion, generate_binary_structure
ImportError: cannot import name 'convolve'

**Comment by songquanpeng** [comment]
Try this one: `scikit-image==0.16.2 & scipy==1.2.1`

The code is actually based on https://github.com/clovaai/stargan-v2.

**Comment by hwd-code** [comment]
请问，现在有test和eval的脚本吗，我执行eval时加载模型出现了问题
Traceback (most recent call last):
  File "D:\DATA\huangwd\L2M-GAN-master1\main.py", line 29, in <module>
    main(cfg)
  File "D:\DATA\huangwd\L2M-GAN-master1\main.py", line 20, in main
    solver.evaluate()
  File "D:\Anaconda\envs\py310env\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\DATA\huangwd\L2M-GAN-master1\solver\solver.py", line 202, in evaluate
    sample_path = self.sample()
  File "D:\Anaconda\envs\py310env\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\DATA\huangwd\L2M-GAN-master1\solver\solver.py", line 189, in sample
    self.load_model(args.eval_iter)
  File "D:\DATA\huangwd\L2M-GAN-master1\solver\solver.py", line 72, in load_model
    ckptio.load(step)
  File "D:\DATA\huangwd\L2M-GAN-master1\utils\checkpoint.py", line 26, in load
    self.load_from_path(fname)
  File "D:\DATA\huangwd\L2M-GAN-master1\utils\checkpoint.py", line 37, in load_from_path
    module.load_state_dict(module_dict[name])
  File "D:\Anaconda\envs\py310env\lib\site-packages\torch\nn\modules\module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Generator:
	Unexpected key(s) in state_dict: "encode.6.conv1.weight", "encode.6.conv1.bias", "encode.6.conv2.weight", "encode.6.conv2.bias", "encode.6.norm1.weight", "encode.6.norm1.bias", "encode.6.norm2.weight", "encode.6.norm2.bias", "encode.2.conv1x1.weight", "decode.6.conv1.weight", "decode.6.conv1.bias", "decode.6.conv2.weight", "decode.6.conv2.bias", "decode.6.norm1.fc.weight", "decode.6.norm1.fc.bias", "decode.6.norm2.fc.weight", "decode.6.norm2.fc.bias", "decode.6.conv1x1.weight". 
	size mismatch for from_rgb.weight: copying a param with shape torch.Size([64, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 3, 3, 3]).
	size mismatch for from_rgb.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for encode.0.conv1.weight: copying a param with shape torch.Size([64, 64, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 128, 3, 3]).
	size mismatch for encode.0.conv1.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for encode.0.conv2.weight: copying a param with shape torch.Size([128, 64, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 128, 3, 3]).
	size mismatch for encode.0.conv2.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for encode.0.norm1.weight: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for encode.0.norm1.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for encode.0.norm2.weight: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for encode.0.norm2.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for encode.0.conv1x1.weight: copying a param with shape torch.Size([128, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([256, 128, 1, 1]).
	size mismatch for encode.1.conv1.weight: copying a param with shape torch.Size([128, 128, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3]).
	size mismatch for encode.1.conv1.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for encode.1.conv2.weight: copying a param with shape torch.Size([256, 128, 3, 3]) from checkpoint, the shape in current model is torch.Size([512, 256, 3, 3]).
	size mismatch for encode.1.conv2.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for encode.1.norm1.weight: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for encode.1.norm1.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for encode.1.norm2.weight: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for encode.1.norm2.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for encode.1.conv1x1.weight: copying a param with shape torch.Size([256, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([512, 256, 1, 1]).
	size mismatch for encode.2.conv1.weight: copying a param with shape torch.Size([256, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([512, 512, 3, 3]).
	size mismatch for encode.2.conv1.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for encode.2.conv2.weight: copying a param with shape torch.Size([512, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([512, 512, 3, 3]).
	size mismatch for encode.2.norm1.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for encode.2.norm1.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for encode.2.norm2.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for encode.2.norm2.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for to_rgb.0.weight: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for to_rgb.0.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for to_rgb.2.weight: copying a param with shape torch.Size([3, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([3, 128, 1, 1]).
